const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const dir=path.join(__dirname,'raw_2026-10-02/candidate_verification');
function hwp(b){if(!b.subarray(0,8).equals(Buffer.from('d0cf11e0a1b11ae1','hex')))return null;const size=2**b.readUInt16LE(30),miniSize=2**b.readUInt16LE(32);if(![512,4096].includes(size)||miniSize!==64)throw Error('Unsupported sector size');
 const sector=id=>{const start=(id+1)*size;if(id>=0xfffffffa||start+size>b.length)throw Error('Invalid sector');return b.subarray(start,start+size);};
 const ints=data=>Array.from({length:Math.floor(data.length/4)},(_,i)=>data.readUInt32LE(i*4));let fatIds=ints(b.subarray(76,512)),difat=b.readUInt32LE(68);for(let n=0;n<Math.min(b.readUInt32LE(72),b.length/size);n++){const ids=ints(sector(difat));fatIds.push(...ids.slice(0,-1));difat=ids.at(-1);}const fat=fatIds.filter(id=>id<0xfffffffa).flatMap(id=>ints(sector(id)));
 const chain=(id,table,reader)=>{const seen=new Set(),chunks=[];while(id<0xfffffffa){if(seen.has(id)||id>=table.length)throw Error('Invalid allocation chain');seen.add(id);chunks.push(reader(id));id=table[id];}return Buffer.concat(chunks);};const directory=chain(b.readUInt32LE(48),fat,sector),entries=[];for(let at=0;at+128<=directory.length;at+=128){const d=directory.subarray(at,at+128),length=Math.min(d.readUInt16LE(64),64);entries.push({name:d.subarray(0,Math.max(length-2,0)).toString('utf16le'),type:d[66],id:d.readUInt32LE(116),length:Number(d.readBigUInt64LE(120))});}const root=entries.find(e=>e.type===5);if(!root)throw Error('Missing root stream');const miniStream=chain(root.id,fat,sector).subarray(0,root.length),miniFat=ints(chain(b.readUInt32LE(60),fat,sector)),cutoff=b.readUInt32LE(56);const stream=e=>(e.length<cutoff?chain(e.id,miniFat,id=>miniStream.subarray(id*miniSize,(id+1)*miniSize)):chain(e.id,fat,sector)).subarray(0,e.length);const headEntry=entries.find(e=>e.name==='FileHeader');if(!headEntry)return null;const header=stream(headEntry);if(!header.subarray(0,17).toString().startsWith('HWP Document File'))return null;const flags=header.readUInt32LE(36);if(flags&2)throw Error('Encrypted document');const paragraphs=[];
 for(const e of entries.filter(e=>e.type===2&&/^Section\d+$/.test(e.name)).sort((a,b)=>a.name.localeCompare(b.name))){let body=stream(e);if(flags&1)body=zlib.inflateRawSync(body);paragraphs.push('[SECTION '+e.name+']');for(let at=0;at+4<=body.length;){const record=body.readUInt32LE(at);at+=4;let length=record>>>20;if(length===4095){length=body.readUInt32LE(at);at+=4;}if(at+length>body.length)throw Error('Truncated HWP record');const payload=body.subarray(at,at+length);at+=length;if((record&1023)!==67)continue;let text='';for(let k=0;k+2<=payload.length;){const value=payload.readUInt16LE(k);if([10,13].includes(value)){text+='\n';k+=2;}else if(value===9){text+='\t';k+=16;}else if([1,2,3,4,5,6,7,8,11,12,14,15,16,17,18,19,20,21,22,23].includes(value))k+=16;else{if(value>=32)text+=String.fromCharCode(value);k+=2;}}paragraphs.push(text);}}
 if(!paragraphs.length)throw Error('No body section;distribution HWP or unsupported document');return paragraphs.join('\n');
}
function hwpx(b){if(b.subarray(0,2).toString()!=='PK')return null;const parts=[];for(let at=0;at+46<b.length;at++){if(b.readUInt32LE(at)!==0x02014b50)continue;const method=b.readUInt16LE(at+10),compressed=b.readUInt32LE(at+20),n=b.readUInt16LE(at+28),extra=b.readUInt16LE(at+30),comment=b.readUInt16LE(at+32),offset=b.readUInt32LE(at+42),name=b.subarray(at+46,at+46+n).toString();if(/^Contents\/section\d+\.xml$/.test(name)){const start=offset+30+b.readUInt16LE(offset+26)+b.readUInt16LE(offset+28),data=b.subarray(start,start+compressed),xml=(method===8?zlib.inflateRawSync(data):data).toString('utf8');parts.push({name,text:xml.replace(/<hp:t\b[^>]*>([\s\S]*?)<\/hp:t>/g,(_,s)=>s+' ').replace(/<\/hp:p>/g,'\n').replace(/<[^>]+>/g,'').replace(/&(amp|lt|gt|quot|apos);/g,(_,s)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[s]))});}at+=45+n+extra+comment;}return parts.length?parts.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>p.text).join('\n'):null;}
const log=path.join(dir,'document_extraction_log.json'),records=fs.existsSync(log)?JSON.parse(fs.readFileSync(log,'utf8')):[];
function archiveDocuments(b,file){if(b.subarray(0,2).toString()!=='PK')return null;const texts=[];for(let at=0;at+46<b.length;at++){if(b.readUInt32LE(at)!==0x02014b50)continue;const method=b.readUInt16LE(at+10),compressed=b.readUInt32LE(at+20),n=b.readUInt16LE(at+28),extra=b.readUInt16LE(at+30),comment=b.readUInt16LE(at+32),offset=b.readUInt32LE(at+42),name=b.subarray(at+46,at+46+n).toString();if(/\.(hwp|hwpx|pdf)$/i.test(name)){if(![0,8].includes(method)||offset+30>b.length||compressed>25000000)throw Error('Unsupported ZIP member');const start=offset+30+b.readUInt16LE(offset+26)+b.readUInt16LE(offset+28),bytes=b.subarray(start,start+compressed),data=method===8?zlib.inflateRawSync(bytes,{maxOutputLength:50000000}):bytes;const member=file+'_member_'+offset+(/\.pdf$/i.test(name)?'.pdf':'.hwp');fs.writeFileSync(path.join(dir,member),data);const text=hwp(data)??hwpx(data);if(text){fs.writeFileSync(path.join(dir,member+'.document.txt'),text);texts.push('[ZIP MEMBER '+name+']\n'+text);}}at+=45+n+extra+comment;}return texts.length?texts.join('\n\n'):null;}
for(const file of fs.readdirSync(dir).filter(f=>/\.(html|hwp|hwpx|zip)$/.test(f))){const output=file+'.document.txt';if(fs.existsSync(path.join(dir,output)))continue;try{const b=fs.readFileSync(path.join(dir,file)),text=hwp(b)??hwpx(b)??archiveDocuments(b,file);if(text===null)continue;fs.writeFileSync(path.join(dir,output),text);records.push({file,textFile:output,characters:text.length,method:'HWP paragraph records, HWPX XML text or ZIP members. Formatting/reading order may differ.'});console.log(file+' '+text.length);}catch(e){records.push({file,error:e.message});}}
fs.writeFileSync(log,JSON.stringify(records,null,2));
