const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {plain}=require('./housing_export_utils.cjs');
const raw=path.join(__dirname,'raw_2026-10-02'),out=path.join(raw,'candidate_verification');fs.mkdirSync(out,{recursive:true});
const policies=[1,2,3,4].flatMap(i=>JSON.parse(fs.readFileSync(path.join(raw,`API_HOUSING_${i}.json`),'utf8')).result.youthPolicyList);
const logFile=path.join(out,'checks.json');const checks=fs.existsSync(logFile)?JSON.parse(fs.readFileSync(logFile,'utf8')):[];
function clean(s){return String(s||'').replace(/\s+/g,'').replace(/&amp;/g,'&');}
function urls(p){return [...new Set([p.refUrlAddr1,p.refUrlAddr2,p.aplyUrlAddr].map(clean).filter(u=>/^https?:\/\//i.test(u)))];}
function excluded(u){return /(?:blog\.naver|cafe\.naver|instagram|facebook|youtube|youtu\.be|pf\.kakao|tistory)\./i.test(new URL(u).hostname+'.');}
async function get(u,id,options={}){const r={URL:u,확인일:process.argv.includes('--recheck291')||process.argv.includes('--date03')?'2026-10-03':'2026-10-02',...(options.method?{조회방법:options.method}:{})};if(excluded(u)){r.error='비공식·SNS 링크:공식 검증근거로 사용하지 않음';return r;}
try{const response=await fetch(u,{...options,signal:AbortSignal.timeout(18000)}),b=Buffer.from(await response.arrayBuffer());r.status=response.status;r.finalURL=response.url;r.bytes=b.length;r.sha256=crypto.createHash('sha256').update(b).digest('hex');const magic=b.subarray(0,4).toString();r.file=id+(magic==='%PDF'?'.pdf':magic.startsWith('PK')?'.zip':'.html');fs.writeFileSync(path.join(out,r.file),b);if(r.file.endsWith('.html')){let html;try{const charset=(response.headers.get('content-type')||'').match(/charset=([^; ]+)/i)?.[1]||(/charset\s*=\s*["']?(euc-kr|ks_c_5601-1987)/i.test(b.toString('ascii'))?'euc-kr':'utf-8');html=new TextDecoder(charset==='ks_c_5601-1987'?'euc-kr':charset).decode(b);}catch{html=b.toString('utf8');}r.textFile=id+'.txt';fs.writeFileSync(path.join(out,r.textFile),plain(html));r.title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]*>/g,'').trim()||'';r.links=[...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>{try{return {URL:new URL(m[1].replace(/&amp;/g,'&'),response.url).href,title:plain(m[2])};}catch{return null;}}).filter(Boolean).filter(l=>/^https?:/.test(l.URL)&&/(모집|공고|정정|추가|재공고|다운로드|첨부|\.pdf|\.hwp|download|fileDown)/i.test(l.title+' '+l.URL));r.errorPage=/접근이 거부|요청하신 페이지를 찾을|존재하지 않는 페이지|Access Denied|403 Forbidden|404 Not Found/i.test(plain(html).slice(0,1500));}
}catch(e){r.error=e.name+': '+e.message;}return r;}
async function verify(p,index){const prior=checks.find(c=>c.plcyNo===p.plcyNo);if(prior&&!prior.자료.some(s=>s.error?.includes('fetch failed')))return;
 const c={plcyNo:p.plcyNo,정책명:p.plcyNm,시행기관:p.sprvsnInstCdNm,확인일:'2026-10-02',API신청기간:p.aplyYmd||'',자료:[]};
 for(const [i,u]of urls(p).entries())c.자료.push(await get(u,p.plcyNo+'_'+i));
 const stem=p.plcyNm.replace(/202\d년?|청년|지원사업|지원|사업|공급|운영|주택|\s|[()]/g,'');
 const links=c.자료.flatMap(s=>s.links||[]).filter(l=>(stem.length>=2&&l.title.includes(stem))||/\.pdf|\.hwpx?|download|fileDown/i.test(l.URL)).filter(l=>!urls(p).includes(l.URL));
 for(const [i,l]of [...new Map(links.map(l=>[l.URL,l])).values()].slice(0,3).entries())c.자료.push({...await get(l.URL,p.plcyNo+'_attached_'+i),リンク見出し:l.title});
 if(prior)checks.splice(checks.indexOf(prior),1);checks.push(c);fs.writeFileSync(logFile,JSON.stringify(checks,null,2));console.log(`${checks.length}/318 ${p.plcyNo} ${c.자료.filter(s=>s.status===200&&!s.errorPage).length}/${c.자료.length} ${p.plcyNm}`);
}
function similarity(a,b){const norm=s=>s.replace(/202\d년?|모집|공고|지원사업|지원|사업|청년|[^가-힣a-zA-Z0-9]/g,'');a=norm(a);b=norm(b);if(!a||!b)return 0;if(b.includes(a))return 1;const pairs=new Set(Array.from({length:Math.max(a.length-1,0)},(_,i)=>a.slice(i,i+2)));return [...pairs].filter(x=>b.includes(x)).length/Math.max(pairs.size,1);}
async function searchSources(){const file=path.join(out,'search_checks.json'),results=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')).filter(x=>x.version===2):[];
 for(let base=0;base<policies.length;base+=6)await Promise.all(policies.slice(base,base+6).map(async p=>{const sfNames=['search_exact_','search_alt_','search_'].map(prefix=>path.join(out,prefix+p.plcyNo+'.json')).filter(f=>fs.existsSync(f));if(!sfNames.length)return;const searches=sfNames.map(f=>JSON.parse(fs.readFileSync(f,'utf8')));const search={query:searches.map(s=>s.query||s.error).join(' | '),raw:searches.map(s=>s.raw||'').join('\n')};if(results.some(x=>x.plcyNo===p.plcyNo&&x.検索語===search.query))return;const found=[...(search.raw||'').matchAll(/(?:^|\n)([^\n]+) \((https?:\/\/[^\n]+)\)\n/g)].map(m=>({title:m[1],URL:m[2],score:similarity(p.plcyNm,m[1])}));let originalHosts=urls(p).map(u=>new URL(u).hostname);const allowed=u=>{const h=new URL(u).hostname;return /\.go\.kr$|\.ac\.kr$/.test(h)||['hf.go.kr','www.kosaf.go.kr','www.jpdc.co.kr','www.gjtp.or.kr','gjtp.or.kr','www.kasfo.or.kr','www.nysc.or.kr','www.gsyouth.or.kr','gsyouth.or.kr'].includes(h)||originalHosts.includes(h);};const candidates=found.filter(x=>x.score>=0.3&&allowed(x.URL)&&!excluded(x.URL)).sort((a,b)=>b.score-a.score).slice(0,3);const c={version:2,plcyNo:p.plcyNo,検索語:search.query,검색결과수:found.length,자료:[]};for(const [i,s]of candidates.entries())c.자료.push({...await get(s.URL,p.plcyNo+'_search_'+crypto.createHash('sha256').update(s.URL).digest('hex').slice(0,10)),검색제목:s.title,제목유사도:s.score});const old=results.findIndex(x=>x.plcyNo===p.plcyNo);if(old>=0)results.splice(old,1);results.push(c);fs.writeFileSync(file,JSON.stringify(results,null,2));console.log('search-source '+results.length+' '+p.plcyNo+' '+c.자료.length);}));
}
async function latestSources(short=false){
 const remaining=short==='remaining';
 const log=path.join(out,remaining?'remaining_checks.json':short?'latest_short_checks.json':'latest_checks.json'),results=fs.existsSync(log)?JSON.parse(fs.readFileSync(log,'utf8')):[];
 const targets=JSON.parse(fs.readFileSync(path.join(out,remaining?'remaining_review_targets_276.json':'latest_review_targets_291.json'),'utf8').replace(/^\uFEFF/,''));
 for(let base=0;base<targets.length;base+=5)await Promise.all(targets.slice(base,base+5).map(async t=>{const p=policies.find(p=>p.plcyNo===t.plcyNo),sf=(remaining?'search_remaining_':short?'search_latest_short_':'search_latest_')+p.plcyNo+'.json';if(!fs.existsSync(path.join(out,sf))||results.some(x=>x.plcyNo===p.plcyNo))return;
  const search=JSON.parse(fs.readFileSync(path.join(out,sf),'utf8')),hosts=urls(p).map(u=>new URL(u).hostname.replace(/^www\./,''));
  const found=[...(search.raw||'').matchAll(/(?:^|\n)([^\n]+) \((https?:\/\/[^\n]+)\)\n/g)].map(m=>({title:m[1],URL:m[2],score:similarity(p.plcyNm,m[1])}));
  const candidates=[...new Map(found.filter(s=>{const h=new URL(s.URL).hostname.replace(/^www\./,'');return s.score>=0.55&&!excluded(s.URL)&&(/\.go\.kr$|\.ac\.kr$/.test(h)||hosts.includes(h));}).sort((a,b)=>b.score-a.score).map(s=>[s.URL,s])).values()].slice(0,4);
  const c={plcyNo:p.plcyNo,정책명:p.plcyNm,검색어:search.query,자료:[],첨부:[],선택기준:'공식 또는 API연결호스트,제목유사도0.55이상 탐색후보;동일사업·최신성 확정 아님'};
  for(const s of candidates){const r={...await get(s.URL,p.plcyNo+'_latest_'+crypto.createHash('sha256').update(s.URL).digest('hex').slice(0,10)),검색제목:s.title,제목유사도:s.score};c.자료.push(r);const attachments=(r.links||[]).filter(l=>/\.pdf|\.hwpx?|download|fileDown|file.*down/i.test(l.URL)&&/공고|모집|정정|추가|붙임|첨부|\.pdf|\.hwpx?/i.test(l.title)).filter(l=>!c.첨부.some(a=>a.URL===l.URL));for(const a of attachments.slice(0,3))c.첨부.push({...await get(a.URL,p.plcyNo+'_latest_attach_'+crypto.createHash('sha256').update(a.URL).digest('hex').slice(0,10)),첨부제목:a.title,부모URL:r.URL});}
  results.push(c);fs.writeFileSync(log,JSON.stringify(results,null,2));console.log('latest-reference '+results.length+'/291 '+p.plcyNo+' pages:'+c.자료.length+' attachments:'+c.첨부.length);
 }));
}
async function manualSources(){const targetFile=process.argv.includes('--guide-notices')?'guide_notice_fetch_targets.json':process.argv.includes('--pending73')?'pending_73_fetch_targets.json':'manual_targets.json';const targets=JSON.parse(fs.readFileSync(path.join(out,targetFile),'utf8')).flat(Infinity);const results=fs.existsSync(path.join(out,'manual_checks.json'))?JSON.parse(fs.readFileSync(path.join(out,'manual_checks.json'),'utf8')):[];for(let base=0;base<targets.length;base+=5){const batch=await Promise.all(targets.slice(base,base+5).map(async t=>{if(results.some(r=>r.plcyNo===t.id&&r.URL===t.URL&&r.status===200))return null;return {plcyNo:t.id,...await get(t.URL,t.id+'_manual_'+crypto.createHash('sha256').update(t.URL).digest('hex').slice(0,10),t.fetchOptions||{})};}));results.push(...batch.filter(Boolean));fs.writeFileSync(path.join(out,'manual_checks.json'),JSON.stringify(results,null,2));console.log('Manual targets '+Math.min(base+5,targets.length)+'/'+targets.length);}console.log('Manual source retrieval: '+results.length);}
async function recheck291(){
 const read=f=>fs.existsSync(path.join(out,f))?JSON.parse(fs.readFileSync(path.join(out,f),'utf8').replace(/^\uFEFF/,'')):[];
 const targets=read('latest_review_targets_291.json'),log=path.join(out,'recheck_2026-10-03.json'),results=read('recheck_2026-10-03.json');
 const previous=['checks.json','search_checks.json','latest_checks.json','latest_short_checks.json','remaining_checks.json'].flatMap(read),manual=read('manual_checks.json');
 const cache=new Map(),fetchOnce=u=>{if(!cache.has(u))cache.set(u,get(u,'recheck03_'+crypto.createHash('sha256').update(u).digest('hex').slice(0,16)));return cache.get(u);};
 for(let base=0;base<targets.length;base+=6)await Promise.all(targets.slice(base,base+6).map(async t=>{
  if(results.some(r=>r.plcyNo===t.plcyNo))return;
  const docs=previous.filter(r=>r.plcyNo===t.plcyNo).flatMap(r=>[...(r.자료||[]),...(r.첨부||[])]).concat(manual.filter(r=>r.plcyNo===t.plcyNo));
  const p=policies.find(p=>p.plcyNo===t.plcyNo),initial=urls(p).filter(u=>!excluded(u)&&!u.includes('youthcenter.go.kr/go/ythip'));
  const extra=docs.filter(r=>r.status===200&&!r.errorPage&&!excluded(r.URL)).sort((a,b)=>similarity(t.정책명,b.검색제목||b.title||b.첨부제목||'')-similarity(t.정책명,a.검색제목||a.title||a.첨부제목||''));
  const chosen=[...new Set([...initial.slice(0,1),...manual.filter(r=>r.plcyNo===t.plcyNo&&r.status===200).map(r=>r.URL).slice(-1),...extra.map(r=>r.URL)])].slice(0,3);
  const record={plcyNo:t.plcyNo,정책명:t.정책명,확인일:'2026-10-03',선택기준:'API공식연결1·확보수동자료1·기존공식후보 중 제목유사도순;최대3원문 및 연결첨부2. 전체게시판 완전탐색 아님',자료:[],첨부:[]};
  for(const u of chosen){const r=await fetchOnce(u);record.자료.push(r);const attachments=(r.links||[]).filter(l=>/\.pdf|\.hwpx?|download|fileDown/i.test(l.URL)&&/공고|모집|정정|추가|붙임|첨부/i.test(l.title));for(const l of attachments.slice(0,2))if(!record.첨부.some(a=>a.URL===l.URL))record.첨부.push({...await fetchOnce(l.URL),첨부제목:l.title,부모URL:u});}
  if(!chosen.length)record.한계='API링크 없음/비공식/일반API 주소,기존 공식원문 후보 미확보';
  results.push(record);fs.writeFileSync(log,JSON.stringify(results,null,2));console.log('recheck '+results.length+'/291 '+t.plcyNo+' '+record.자료.length+'/'+record.첨부.length);
 }));
}
(async()=>{if(process.argv.includes('--recheck291'))await recheck291();else if(process.argv.includes('--remaining'))await latestSources('remaining');else if(process.argv.includes('--latest-short'))await latestSources(true);else if(process.argv.includes('--latest'))await latestSources();else if(process.argv.includes('--manual'))await manualSources();else if(process.argv.includes('--search'))await searchSources();else for(let i=0;i<policies.length;i+=6)await Promise.all(policies.slice(i,i+6).map(verify));console.log('Evidence retrieval finished. HTTP success and title similarity do not establish latest notice or eligibility.');})();
