const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {plain}=require('./housing_export_utils.cjs');
const raw=path.join(__dirname,'raw_2026-10-02'),out=path.join(raw,'candidate_verification');fs.mkdirSync(out,{recursive:true});
const policies=[1,2,3,4].flatMap(i=>JSON.parse(fs.readFileSync(path.join(raw,`API_HOUSING_${i}.json`),'utf8')).result.youthPolicyList);
const logFile=path.join(out,'checks.json');const checks=fs.existsSync(logFile)?JSON.parse(fs.readFileSync(logFile,'utf8')):[];
function clean(s){return String(s||'').replace(/\s+/g,'').replace(/&amp;/g,'&');}
function urls(p){return [...new Set([p.refUrlAddr1,p.refUrlAddr2,p.aplyUrlAddr].map(clean).filter(u=>/^https?:\/\//i.test(u)))];}
function excluded(u){return /(?:blog\.naver|cafe\.naver|instagram|facebook|youtube|youtu\.be|pf\.kakao|tistory)\./i.test(new URL(u).hostname+'.');}
async function get(u,id){const r={URL:u,확인일:'2026-10-02'};if(excluded(u)){r.error='비공식·SNS 링크:공식 검증근거로 사용하지 않음';return r;}
try{const response=await fetch(u,{signal:AbortSignal.timeout(18000)}),b=Buffer.from(await response.arrayBuffer());r.status=response.status;r.finalURL=response.url;r.bytes=b.length;r.sha256=crypto.createHash('sha256').update(b).digest('hex');const magic=b.subarray(0,4).toString();r.file=id+(magic==='%PDF'?'.pdf':magic.startsWith('PK')?'.zip':'.html');fs.writeFileSync(path.join(out,r.file),b);if(r.file.endsWith('.html')){let html;try{const charset=(response.headers.get('content-type')||'').match(/charset=([^; ]+)/i)?.[1]||(/charset\s*=\s*["']?(euc-kr|ks_c_5601-1987)/i.test(b.toString('ascii'))?'euc-kr':'utf-8');html=new TextDecoder(charset==='ks_c_5601-1987'?'euc-kr':charset).decode(b);}catch{html=b.toString('utf8');}r.textFile=id+'.txt';fs.writeFileSync(path.join(out,r.textFile),plain(html));r.title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]*>/g,'').trim()||'';r.links=[...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>{try{return {URL:new URL(m[1].replace(/&amp;/g,'&'),response.url).href,title:plain(m[2])};}catch{return null;}}).filter(Boolean).filter(l=>/^https?:/.test(l.URL)&&/(모집|공고|정정|추가|재공고|다운로드|첨부|\.pdf|\.hwp|download|fileDown)/i.test(l.title+' '+l.URL));r.errorPage=/접근이 거부|요청하신 페이지를 찾을|존재하지 않는 페이지|Access Denied|403 Forbidden|404 Not Found/i.test(plain(html).slice(0,1500));}
}catch(e){r.error=e.name+': '+e.message;}return r;}
async function verify(p,index){const prior=checks.find(c=>c.plcyNo===p.plcyNo);if(prior&&!prior.자료.some(s=>s.error?.includes('fetch failed')))return;
 const c={plcyNo:p.plcyNo,정책명:p.plcyNm,시행기관:p.sprvsnInstCdNm,확인일:'2026-10-02',API신청기간:p.aplyYmd||'',자료:[]};
 for(const [i,u]of urls(p).entries())c.자료.push(await get(u,p.plcyNo+'_'+i));
 const stem=p.plcyNm.replace(/202\d년?|청년|지원사업|지원|사업|공급|운영|주택|\s|[()]/g,'');
 const links=c.자료.flatMap(s=>s.links||[]).filter(l=>(stem.length>=2&&l.title.includes(stem))||/\.pdf|\.hwpx?|download|fileDown/i.test(l.URL)).filter(l=>!urls(p).includes(l.URL));
 for(const [i,l]of [...new Map(links.map(l=>[l.URL,l])).values()].slice(0,3).entries())c.자료.push({...await get(l.URL,p.plcyNo+'_attached_'+i),リンク見出し:l.title});
 if(prior)checks.splice(checks.indexOf(prior),1);checks.push(c);fs.writeFileSync(logFile,JSON.stringify(checks,null,2));console.log(`${checks.length}/318 ${p.plcyNo} ${c.자료.filter(s=>s.status===200&&!s.errorPage).length}/${c.자료.length} ${p.plcyNm}`);
}
function similarity(a,b){const norm=s=>s.replace(/202\d년?|모집|공고|지원사업|지원|사업|청년|[^가-힣a-zA-Z0-9]/g,'');a=norm(a);b=norm(b);if(!a||!b)return 0;if(b.includes(a))return 1;const pairs=new Set(Array.from({length:Math.max(a.length-1,0)},(_,i)=>a.slice(i,i+2)));return [...pairs].filter(x=>b.includes(x)).length/Math.max(pairs.size,1);}
async function searchSources(){const file=path.join(out,'search_checks.json'),results=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')).filter(x=>x.version===2):[];
 for(let base=0;base<policies.length;base+=6)await Promise.all(policies.slice(base,base+6).map(async p=>{const sfNames=['search_exact_','search_alt_','search_'].map(prefix=>path.join(out,prefix+p.plcyNo+'.json')).filter(f=>fs.existsSync(f));if(!sfNames.length)return;const searches=sfNames.map(f=>JSON.parse(fs.readFileSync(f,'utf8')));const search={query:searches.map(s=>s.query||s.error).join(' | '),raw:searches.map(s=>s.raw||'').join('\n')};if(results.some(x=>x.plcyNo===p.plcyNo&&x.検索語===search.query))return;const found=[...(search.raw||'').matchAll(/(?:^|\n)([^\n]+) \((https?:\/\/[^\n]+)\)\n/g)].map(m=>({title:m[1],URL:m[2],score:similarity(p.plcyNm,m[1])}));let originalHosts=urls(p).map(u=>new URL(u).hostname);const allowed=u=>{const h=new URL(u).hostname;return /\.go\.kr$|\.ac\.kr$/.test(h)||['hf.go.kr','www.kosaf.go.kr','www.jpdc.co.kr','www.gjtp.or.kr','gjtp.or.kr','www.kasfo.or.kr','www.nysc.or.kr','www.gsyouth.or.kr','gsyouth.or.kr'].includes(h)||originalHosts.includes(h);};const candidates=found.filter(x=>x.score>=0.3&&allowed(x.URL)&&!excluded(x.URL)).sort((a,b)=>b.score-a.score).slice(0,3);const c={version:2,plcyNo:p.plcyNo,検索語:search.query,검색결과수:found.length,자료:[]};for(const [i,s]of candidates.entries())c.자료.push({...await get(s.URL,p.plcyNo+'_search_'+crypto.createHash('sha256').update(s.URL).digest('hex').slice(0,10)),검색제목:s.title,제목유사도:s.score});const old=results.findIndex(x=>x.plcyNo===p.plcyNo);if(old>=0)results.splice(old,1);results.push(c);fs.writeFileSync(file,JSON.stringify(results,null,2));console.log('search-source '+results.length+' '+p.plcyNo+' '+c.자료.length);}));
}
async function manualSources(){const targets=JSON.parse(fs.readFileSync(path.join(out,'manual_targets.json'),'utf8'));const results=[];for(const t of targets)results.push({plcyNo:t.id,...await get(t.URL,t.id+'_manual')});fs.writeFileSync(path.join(out,'manual_checks.json'),JSON.stringify(results,null,2));console.log('Manual source retrieval: '+results.length);}
(async()=>{if(process.argv.includes('--manual'))await manualSources();else if(process.argv.includes('--search'))await searchSources();else for(let i=0;i<policies.length;i+=6)await Promise.all(policies.slice(i,i+6).map(verify));console.log('Evidence retrieval finished. HTTP success and title similarity do not establish latest notice or eligibility.');})();
